### ISSUE TITLE
android ChooserActivity ContentProvider Permissions Denial

### ISSUE THREAD

**Issue by teleportal-andrew** [natsuite/NatShare#121] opened 2021-08-27 19:12 UTC
I am encountering the following on android from the ChooserActivity
`2021-08-27 11:15:22.896 1503-1605/? D/EventSequenceValidator: Transition from ACTIVITY_LAUNCHED to ACTIVITY_FINISHED
2021-08-27 11:15:22.900 12042-12061/? E/DatabaseUtils: Writing exception to parcel
    java.lang.SecurityException: Permission Denial: reading androidx.core.content.FileProvider uri content://my.app.uri.natshare/external/recording_2021_08_27_11_14_41_103.mp4 from pid=12241, uid=1000 requires the provider be exported, or grantUriPermission()
        at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:820)
        at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:684)
        at android.content.ContentProvider$Transport.query(ContentProvider.java:239)
        at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:106)
        at android.os.Binder.execTransactInternal(Binder.java:1154)
        at android.os.Binder.execTransact(Binder.java:1123)
2021-08-27 11:15:22.901 12241-12241/? W/ChooserActivity: Could not load (content://my.app.uri.natshare/external/recording_2021_08_27_11_14_41_103.mp4) thumbnail/name for preview. If desired, consider using Intent#createChooser to launch the ChooserActivity, and set your Intent's clipData and flags in accordance with that method's documentation`

I believe to overcome this, i need to add a `<provider></provider>` tag to the manifest such as:
`<provider android:authorities="my.app.uri.natshare" android:exported="true" android:name="com.natsuite.natshare.???" android:readPermission="true" />`

[edit] - I see now these are provided in https://github.com/natsuite/NatShare/blob/1.2/Android/NatShare/src/main/AndroidManifest.xml - with inline permissions, so perhaps there's another underlying issue at play here

however I haven't been able to track down the class name to provide for android:name

is this the proper approach to resolving the permission error, or is there an alternative I've perhaps missed

thanks!

**Comment by olokobayusuf** [comment] 2021-08-28 12:02
Hey @teleportal-andrew, can you try exporting the Unity project to a Gradle project instead of building an APK directly from Unity? If you inspect the generated Android manifest, that will show whether Unity might not be adding the `<provider>` tag to the final manifest.

> however I haven't been able to track down the class name to provide for android:name

https://github.com/natsuite/NatShare/blob/36ab10097f6dbf7968cd517b5b1aee9b24cd4df1/Android/NatShare/src/main/java/api/natsuite/natshare/SharePayload.java#L103-L112

**Comment by teleportal-andrew** [comment] 2021-08-30 20:03
Here's what I see in the merged android manifest:
`        <provider
            android:name="androidx.core.content.FileProvider"
            android:authorities="my.app.uri.natshare"
            android:exported="false"
            android:grantUriPermissions="true" >
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/filepaths" />
        </provider>`

Though it seems here `androidx.core.content.FileProvider` is used as the "class name" that I was trying to track down above

It may be worth noting that the share chooser is able to share the file - this error message is specifically related to being able to preview the file from the chooser

I spent some time trying different modifications - setting android:readPermissions on the provider, using `grantUriPermission(...)` from addMedia explicitly, adding `FLAG_GRANT_READ_URI_PERMISSION` to Intent chooser directly after `Intent.createChooser(...)` all without results

as far as I can tell from the documentation, provider in manifest file and chooser codebase look correct
Android Version is 11 build number RP1A.201005.004

my only (crude) guess at the moment is that file preview comes from a separate app bundle that also needs permissions granted

**Comment by olokobayusuf** [comment] 2021-09-06 00:17
> It may be worth noting that the share chooser is able to share the file - this error message is specifically related to being able to preview the file from the chooser

This is critical info then. Looks like the issue is that the preview image doesn't show up? If so, it's probably some quirk with Android. Issues like these are pretty difficult to debug, because there's poor documentation on how it is expected to behave.

> my only (crude) guess at the moment is that file preview comes from a separate app bundle that also needs permissions granted

I believe this is internal to Android. I'm closing this issue.

**Closed by olokobayusuf** 2021-09-06 00:17 UTC
